name: Docker Image Publish

on:
  pull_request:
    branches:
      - develop
env:
  PR_NUMBER: ${{ github.event.number }} 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification Build and Pushlish Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: (SUCCESS) Build and Push Images
          SLACK_COLOR: good
          SLACK_MESSAGE: 'Push Docker image to Docker Hub success :rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }} # name bạn config tại lúc new secret ở github

      - name: Slack Notification Build and Pushlish Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: (FAILURE) Build and Push Images 
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Push Docker image to Docker Hub failure :skull:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }} # name bạn config tại lúc new secret ở github
